### ISSUE TITLE
Suggestion: linking servers to specific reactions

### ISSUE THREAD

**Issue by Salvi0** [MMPlugins/ReactionThreads#7]
It would be very nice if during the setup command "rtAdd" an optional server id can be provided after the category one. So in case of multiple mainServerIds and the reporting user is in both of them, he can choose from wich one he is actually asking for help.

**Comment by DarkView** [comment]
I don't quite understand what you are asking for here.
The categoryId already allows you to route threads to different inbox server categories depending on source server - this seems to be what you are requesting. I can't see in what other context you would use the serverId other then category routing.

**Comment by Salvi0** [comment]
Initially I didn't though about the category thing forgive me. But now I had the idea of creating some sort of sub-menu for specific server so I opened a new suggestion over [here](https://github.com/YetAnotherConnor/ReactionThreadsMenu/issues/1)
